const mongoose = require('mongoose');

const LoadSchema = new mongoose.Schema({
    userId: { type: String, required: true },
    email: { type: String, required: true },
    loadId: { type: String,  },
    type: { type: String,  },
    subType: { type: String,  },
    title: { type: String,  },
    status: { type: String,  default: "Pending" },
    price: { type: Number,  },
    pickupLocation: { type: String,  },
    pickupDate: { type: Date,  },
    pickupTime: { type: String,  },
    deliveryLocation: { type: String,  },
    deliveryDate: { type: Date,  },
    deliveryTime: { type: String,  },
    description: { type: String,   },
    typeOfPackaging: { type: String,   },
    quantity: { type: Number,   },
    weight: { type: Number,   },
    length: { type: Number,  },
    width: { type: Number,   },
    height: { type: Number,   },
    bidsQuantity: { type: Number, default: 0 },
    avgPrice: { type: Number, default: 0 },
    bids: [{
        carrierId: { type: String },
        carrierCompanyName: { type: String },
        bidPrice: { type: String },
        aiMadeBid: { type: Boolean, default: false, required: false },
        letter: { type: String },
        estimatedDeliveryTime: { type: String },
        createdAt: { type: Date, default: Date.now },
    }],
    milesTrip: { type: Number,  },
    assignedDriver: {
        driverId: { type: String },
        lat: { type: Number },
        lng: { type: Number },
        avatar: { type: String }
    },
    vehicleYear: { type: String,  },
    vehicleMake: { type: String,  },
    vehicleModel: { type: String,  },
    images: { type: [String]},
    typeOfBusinessLocation: { type: String },
    totalSquareFootage: { type: String },
    numberOfWorkstations: { type: String },
    numberOfLargeOfficeEquipment: { type: String },
    pickupFloorLevel: { type: String },
    deliveryFloorLevel: { type: String },
    specialMovingNeeds: { type: String },
    isOnTrailer: { type: Boolean },
    isStackable: { type: Boolean },
    isHazardous: { type: Boolean },
    rvType: { type: String },
    typeOfResidence : { type: String },
    numberOfBedrooms: { type: String },
    pickupStories   : { type: String },
    deliveryStories : { type: String },
    hasTrailerPreference: { type: Boolean },
    liftGate: { type: Boolean },
    palletJack: { type: Boolean },
    movingRamp: { type: Boolean },
    deliveryPoint: { type: Boolean },
    callBeforeDelivery: { type: Boolean },
    trailerPreferences: [],
    typeUnits: [],
    typeOfHeavyEquipment: [],
    heavyEquipmentCategory: [],
    loadTypeOfTrailer: { type: String,  },
    isConvertible: {type: Boolean},
    isEnclosed: {type: Boolean},
    isFlatbed: {type: Boolean},
    isModified: {type: Boolean},
    isInoperable: {type: Boolean},
    isTrike: {type: Boolean},
    isSidecar: {type: Boolean},
    openTrailer: {type: Boolean},
    enclosedTrailer: {type: Boolean},
    bothOpenAndEnclosed: {type: Boolean},
    typeOfItemsToMove: { type: String },
    estimatedWeightPerItem: { type: String },
    totalNumberOfHeavyItems: { type: String },
    isElevatorAvailable: { type: String },
    distanceToMove: { type: String },
    disassemblyReassembly: { type: Boolean },
    useOfMovingEquipment: { type: Boolean },
    needAdditionalCrew: { type: Boolean },
    emergencyMoving: { type: Boolean },
    totalNumberOfBoxes: { type: String },
    largeFurnitureItems: { type: [String] },
    appliancesBeingMoved: { type: [String] },
    doYouHaveFragileItems: { type: String },
    specialHandlingRequired: { type: [String] },
    furnitureDisassemblyReassembly: { type: Boolean },
    needExtraMovingSupplies: { type: Boolean },
    typeOfOfficeSpace: { type: String },
    numberOfLargeOfficeFurnitureItems: { type: String },
    doesYourOfficeHaveFragileItems: { type: String },
    computers: { type: Boolean },
    printers: { type: Boolean },
    copiers: { type: Boolean },
    phones: { type: Boolean },
    servers: { type: Boolean },
    otherOfficeEquipment: { type: Boolean },
    itEquipment: { type: Boolean },
    serverRacks: { type: Boolean },
    glassPartitions: { type: Boolean },
    electronics: { type: Boolean },
    heavyMachinery: { type: Boolean },
    otherSpecialHandling: { type: Boolean },
    afterHoursOrWeekendMoving: { type: Boolean },
    doYouNeedHelpAssemblingDisassemblingFurniture: { type: String },
    chair: { type: Boolean },
    bookshelf: { type: Boolean },
    miniFridge: { type: Boolean },
    tv: { type: Boolean },
    laptop: { type: Boolean },
    desktopPC: { type: Boolean },
    monitor: { type: Boolean },
    tvElectronics: { type: Boolean },
    gamingConsole: { type: Boolean },
    speakers: { type: Boolean },
    neededDriverAssistance: { type: Boolean },
    neededDriverAssistanceDetails: { type: String },
    otherElectronics: { type: Boolean },
    temporaryStorageNeeded: { type: Boolean },
    needMovingSupplies: { type: Boolean },
    helpWithHeavyLifting: { type: Boolean },
    lastMinuteOrEmergencyMove: { type: Boolean },
    typeOfMilitaryMove: { type: String },
    totalHouseholdSize: { type: String },
    bed: { type: Boolean },
    sofa: { type: Boolean },
    diningTable: { type: Boolean },
    wardrobe: { type: Boolean },
    desk: { type: Boolean },
    dresser: { type: Boolean },
    bookshelves: { type: Boolean },
    otherLargeItems: { type: Boolean },
    refrigerator: { type: Boolean },
    washerDryer: { type: Boolean },
    microwave: { type: Boolean },
    dishwasher: { type: Boolean },
    oven: { type: Boolean },
    otherAppliances: { type: Boolean },
    truckSize: { type: String },
    whatToTransport: { type: String },
    specialRequirements: { type: String },
    loadingHelp: { type: String },
    stairsOrElevator: { type: String },
    extraOptions: { type: [String] },
    uniformsGear: { type: Boolean },
    weaponsFirearms: { type: Boolean },
    storageContainers: { type: Boolean },
    safe: { type: Boolean },
    otherMilitaryItems: { type: Boolean },
    temporaryStorage: { type: Boolean },
    specialPacking: { type: Boolean },
    chosenCarrier: {
        carrierCompanyName: String,
        carrierAvatarUrl: String,
        chatId: String },
    expeditedMoving: { type: Boolean },
    assistanceWithPaperwork: { type: Boolean },
    packingLevel: { type: Number, default: 0 },
    packingUnpackingServices: { type: Boolean },
    unpacking: { type: Boolean, default: false },
    storageNeeds: { type: Boolean },
    storageAmount: { type: Number, default: 0 },
    climateControlled: { type: Boolean },
    insurance: { type: Boolean },
    longTerm: { type: Boolean },
    totalLoadPrice: { type: Number, default: 0 },
    distance: { type: Number, default: 0 },
    stops: [{
        stopLocation: { type: String },
        stopTime: { type: String }
    }],
    createdAt: { type: Date, default: Date.now },
    bookingHash: {
        type: String,
        unique: true,
        sparse: true
    },
}, { timestamps: true });

module.exports = mongoose.model('Load', LoadSchema);